### ISSUE TITLE
Unable to save icon: "The file doesn't exist"

### ISSUE THREAD

**Issue by gingerbeardman** [lemonmojo/IconComposer2x#4]
video: https://transfer.sh/9gdwx/video.mov (available for 14 days)

I have had this on Sierra and also have it on High Sierra GM.

Using latest version 1.1

I cannot save an icon at all.

<img width="435" alt="screen shot 2017-09-22 at 17 23 37" src="https://user-images.githubusercontent.com/49612/30754492-ccdefd90-9fba-11e7-855a-04319b266432.png">

I cannot save the icon to anywhere in my home folder.

However, if I try to save it to the root of my drive it appears to have saved. But no file is actually there if you check, so trying to save any modifications gets the same error.

<img width="435" alt="screen shot 2017-09-22 at 17 22 33" src="https://user-images.githubusercontent.com/49612/30754474-bc05b1c6-9fba-11e7-9f67-0eea5da83e44.png">

**Comment by lemonmojo** [comment]
Hey!

I tried to reproduce the problem on two different machines, one running 10.12.6, with the other at 10.13.1 Beta. Both correctly save the icon file even if I only specify a 64x64 image.

Could you please:
* Send me the image file you're trying to use
* Try running the current master from Xcode and send me any output Xcode spits out while running the app

thx,
felix

**Comment by gingerbeardman** [comment]
I get this using `File > New > Save` (blank icon)

And also `File > New > Paste image > Save` (any icon)

Running the app directly from Xcode...

this is the main error:

```
objc[1067]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffb29c8a70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1062f0cd8). One of the two will be used. Which one is undefined.
```
reference: https://github.com/lionheart/openradar-mirror/issues/17659

other errors on dismissing warning
```
2017-09-28 12:34:28.995078+0100 iconutil[1075:63792] [default] No resources
2017-09-28 12:34:28.995906+0100 iconutil[1075:63792] [default] Failed to write ICNS data to URL file:///var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/TemporaryItems/(A%20Document%20Being%20Saved%20By%20Icon%20Composer%202x)/Untitled.icns with error: (null)
/var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/422A1AF1-01BD-458A-AE85-7973887F93D2-IconComposer2x.iconset:Failed to generate ICNS.
2017-09-28 12:34:30.665814+0100 Icon Composer 2x[1067:63599] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
```
the PluginKit error is strange

Console:
```
default	12:33:55.263886 +0100	Icon Composer 2x	Adding presenter 127964BD-EF49-4FA7-9512-6D4E1E127CBE for URL: (null)
default	12:33:55.264203 +0100	Icon Composer 2x	Adding presenter 127964BD-EF49-4FA7-9512-6D4E1E127CBE for URL: (null)
default	12:34:02.872445 +0100	Icon Composer 2x	WiFi Platform capabilities 30000.
default	12:34:02.872479 +0100	Icon Composer 2x	Device supports Legacy P2P
default	12:34:05.087034 +0100	Icon Composer 2x	LSExceptions shared instance invalidated for timeout.
default	12:34:28.972137 +0100	Icon Composer 2x	Write options: 0 -- URL: file:///Users/matt/Desktop/Untitled.icns -- purposeID: 127964BD-EF49-4FA7-9512-6D4E1E127CBE -- claimID: 839DA52D-156C-456A-90BB-FA04ABD6E7E7
default	12:34:28.973087 +0100	Icon Composer 2x	Claim 839DA52D-156C-456A-90BB-FA04ABD6E7E7 granted in client
default	12:34:28.973130 +0100	Icon Composer 2x	Claim 839DA52D-156C-456A-90BB-FA04ABD6E7E7 invoked in client
default	12:34:29.334938 +0100	Icon Composer 2x	Adding presenter 9B5E321C-FEE2-47D8-8A56-79D710EEA302 for URL: file:///Users/matt/Desktop/
default	12:34:30.665878 +0100	Icon Composer 2x	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(ficl,askM handler=0x7fff6aaabba5 isSys=NO) err=0/noErr
error	12:34:30.665927 +0100	Icon Composer 2x	errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
default	12:34:32.000983 +0100	Icon Composer 2x	Removing presenter 127964BD-EF49-4FA7-9512-6D4E1E127CBE
default	12:34:32.001091 +0100	Icon Composer 2x	Removing presenter 127964BD-EF49-4FA7-9512-6D4E1E127CBE
```

**Comment by gingerbeardman** [comment]
Have cleaned up (reduced) my prior comment

**Comment by gingerbeardman** [comment]
Another lead about the PluginKit error

https://stackoverflow.com/questions/44465904/photopicker-discovery-error-error-domain-pluginkit-code-13

**Comment by gingerbeardman** [comment]
Any thoughts?

**Comment by lemonmojo** [comment]
No, unfortunately not. I tried to reproduce this on 3 different Macs but none of them showed this behavior. If you have another Mac available, please try to reproduce it there. If you don't have another Mac, please try to create a new user account instead and try to reproduce it with that account.

**Comment by gingerbeardman** [comment]
I can reproduce on a Guest account.

I'll try to get locate another Mac to try it on. 

What do you make of the errors?

**Comment by lemonmojo** [comment]
So I just pushed a [commit](https://github.com/lemonmojo/IconComposer2x/commit/65d7757730b14b2b0df34dc77cf7bf0c487174db) with improved error handling. Could you please pull the changes and rebuild and then let me know what happens on your side?

**Comment by gingerbeardman** [comment]
Saving blank icon:

![screen shot 2017-10-05 at 17 04 46](https://user-images.githubusercontent.com/49612/31237627-68ec4c68-a9ef-11e7-8a66-03dbf1c29045.png)


```
objc[4755]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa34c5a70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1052cccd8). One of the two will be used. Which one is undefined.
2017-10-05 17:04:54.169909+0100 Icon Composer 2x[4755:682820] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
```

Still trying to source another Mac

**Comment by lemonmojo** [comment]
Well, a blank icon can't be saved because iconutil doesn't allow that. Why would you do that anyway?!
Please fill all the image fields with matching icons in their respective sizes and try again.

**Comment by gingerbeardman** [comment]
Just to confirm that adding images allows me to save the icon.

However there's another issue: https://github.com/lemonmojo/IconComposer2x/issues/5
